name: VoteLogger
main: main.java.net.bigbadcraft.votelogger.VoteLogger
version: 1.1
author: [BigBadHenz]
commands:
  votelogger:
    description: Displays top votes for the month.
    permission: votelogger.use
    aliases: [vl, vlogger]